### ISSUE TITLE
Seahags spawn in the daytime.

### ISSUE THREAD

**Issue by wasdspace** [FuGu0416/Fishs_Undead_Rising#127]
![2022-12-23_10 49 02](https://user-images.githubusercontent.com/85009668/209266372-4266d029-d1a9-48d6-b5a0-269747c93817.png)
As the title, then they get burned.

**Comment by DigitalWendigo** [comment]
I can't seem to reproduce this. 
Was bored and figured I'd test this and they still only ever spawn at night time. 
(By the way you can disable FUR mobs from burning in daylight in the config file.)
Though I would arguably agree that if they followed the spawning rules of Drowned, they should also never burn in day light regardless of where they are since drowned never burn in daylight either.

**Comment by FuGu0416** [comment]
They might just spawn in the deep ocean (either shipwreck or ocean ruins) and then fly up in to the air.

**Comment by wasdspace** [comment]
> I can't seem to reproduce this. Was bored and figured I'd test this and they still only ever spawn at night time. (By the way you can disable FUR mobs from burning in daylight in the config file.) Though I would arguably agree that if they followed the spawning rules of Drowned, they should also never burn in day light regardless of where they are since drowned never burn in daylight either.

Weird... Almost every time I create a world and then fly to the beach I see them burning (it's still daytime). Maybe some performance mods are messing with them.

**Comment by wasdspace** [comment]
> They might just spawn in the deep ocean (either shipwreck or ocean ruins) and then fly up in to the air.

Yeah, maybe you're right... But I think it would be better for them to have the AI that hides from the sun. Like diving into the water?

**Comment by DigitalWendigo** [comment]
Alright I can finally confirm this. 
They do spawn at coasts during the day time. 
Technically this isn't a major issue but it can become a bit of a problem for anyone that gets close to a beach. 
Since up to two can spawn with the default spawn weights. 
And they don't stay near the beach either, they roam the nearest biome that the beach is part of, or the sea. 


I suggest that instead of giving them a new AI to search for water, to just make them always immune to sunlight. 
**I think Drowned mobs in general should never burn in sunlight for the obvious reason that they're always wet, but that's just a personal thought.**
