### ISSUE TITLE
[Suggestion] Reduce Bomb Projectiles' "Float"

### ISSUE THREAD

**Issue by SandwichHorror** [FuGu0416/Fishs_Undead_Rising#25]
The holy hand grenade, sonic bomb, and ghost bomb all have very low "gravity" when thrown, making them feel more like very light and heavily inflated balloons rather than thrown weapons. If thrown far up, it can take many seconds just for the bomb to hit the ground, which is both frustrating to use in combat and pretty silly looking.

I would strongly recommend reducing the "floatiness" of these projectiles for these reasons.

**Comment by Avlyssna** [comment]
I'm actually in agreement. The float on some of the other grenades is a bit too much. I've left the floaty-ness on the ghost bomb however, since it seems eerie and spooky that way. I mean, it's a ghost bomb after all!

I may add in particle effects while it travels too -- that might be a cool visual feature. For now, here's what the tweaked floats look like. What do you think @FuGu0416?

https://user-images.githubusercontent.com/7981517/104110928-2f7f8d00-52a2-11eb-94a6-25f2d2ac8ccf.mp4
