### ISSUE TITLE
[1.2.3, Compatibility] Sound Filters

### ISSUE THREAD

**Issue by Ameranth** [FuGu0416/Fishs_Undead_Rising#60]
Hello and thank you for your work!

[Sound Filters](https://www.curseforge.com/minecraft/mc-mods/sound-filters) mod with occlusion config on causes gradual and massive FPS loss as sounds from Undead Rising mobs are played.
Confirmed this issue with _only_ Undead Rising and Sound Filters loaded.

This can be reproduced by the following in a new world:
 - Spawn a 3-4 hundred or more parasites (using a command block is how I tested).
 - Let them die.
 - Travel away in a straight line, the FPS loss will become severe as you move away.

**Comment by Avlyssna** [comment]
I almost wonder if this is an bug on the sound filters side of things: since I would logically think it to be their mod producing the FPS drops. That being said, there is a possibility we could be at fault. I'm pretty sure that we do anything out of the ordinary with sounds, but I'll look into it sometime next week.

**Comment by Ameranth** [comment]
Thank you for the reply,

I did also post this issue on their page, but there was no reply yet.

I also think it is their mod producing the FPS drop, but I didn't notice the FPS drop with vanilla mobs or mobs from a few other mods. It's definitely possible that other mods could have a similar problem though, it's hard to know for sure.

But again thank you for taking the time to look into this.

**Comment by Avlyssna** [comment]
I tried to replicate your issue, but I didn't notice anything incredibly abnormal compared to vanilla Minecraft's FPS loss. The bigger issue seems to be vanilla Minecraft's sound engine.

Interestingly, when I spawned about 300 zombies for testing (without sound filters), I could see the FPS was dropping about 80 frames: presumably due to the cost of running 300 zombie AIs. When I got close enough to hear sounds however, it dropped another 35 frames: presumably due to the cost of playing 300 zombie sound effects. This meant I was dropping about 115 frames in total when I was close enough for it to play sounds.

Honestly, I'm ready to pin it on Minecraft's sound engine having trouble playing so many mob sounds and that being worsened with pre-processing from the sound filters mod.

Were you running this on a server? And what were you doing initially that made you suspect there were significant FPS drops?

**Comment by Ameranth** [comment]
Thank you for investigating!

I was running this on a single player world for reproducing the issue, but originally experienced the problem in a LAN game with a couple other people; I first noticed the FPS drop while exploring away from our base.

Note that the issue doesn't happen with minecraft:zombie, and was most easily reproduced with mod_lavacow:parasite.
Also the FPS drop in my reproduction tests happens _after_ the entities have died and stopped producing sounds; as the player tries to travel away from where they died.

Either way, if you can't reproduce the problem then I can only thank you again for trying, you've done more than most do!

**Comment by Avlyssna** [comment]
Maybe I misunderstood then; I'll try once more to reproduce it. However, if I can't get it to trigger, I'm not sure what else I can do unfortunately. I'll let you know if I can get it to happen or not.

**Comment by Ameranth** [comment]
Very well, thank you for your time!
